apiVersion: apps/v1
kind: Deployment
metadata:
  name: golf-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golf-app
  template:
    metadata:
      labels:
        app: golf-app
    spec:
      containers:
      - name: flask-app
        image: gcr.io/golf-app-project-416715/golf_app:v1.0
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: MYSQL_HOST
          value: "mysql_db"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "P@ssword"
        - name: MYSQL_DATABASE
          value: "golf_db"
        - name: POSTGRES_HOST
          value: "postgres_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "P@ssword"
        - name: POSTGRES_DB
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: golf-app
spec:
  selector:
    app: golf-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer